const LIVE_API_URL = "https://signalgeniusai-production.up.railway.app/signal/latest";
const SB_URL = "https://wttsaprezgvircanthbk.supabase.co/rest/v1/fx_signals";
const SB_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0dHNhcHJlemd2aXJjYW50aGJrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODM2ODA3MCwiZXhwIjoyMDgzOTQ0MDcwfQ.QGewz8bDfBC6vJce6g4-sHA164bL1y0u71d6HH7PYVk";

let activeTab = 'active';

// --- UTILS ---

function calculateRR(entry, sl, tp, direction) {
    if (!entry || !sl || !tp) return "n/a";
    try {
        const r = Math.abs(entry - sl);
        const rwd = Math.abs(tp - entry);
        if (r === 0) return "1.00";
        return (rwd / r).toFixed(2);
    } catch (e) { return "n/a"; }
}

function getTradingViewLink(symbol, timeframe) {
    if (!symbol) return "#";
    const cleanSymbol = symbol.replace('/', '');
    const tvSymbol = cleanSymbol.includes(':') ? cleanSymbol : `FX:${cleanSymbol}`;
    const tf = timeframe ? timeframe.replace('M', '') : '15';
    return `https://www.tradingview.com/chart/?symbol=${tvSymbol}&interval=${tf}`;
}

async function copySignalToClipboard(sig) {
    if (!sig) return;
    const dt = new Date(sig.generated_at || sig.timestamp || new Date());
    const timeStr = dt.toISOString().replace('T', ' ').slice(0, 19) + ' UTC';
    const entry = sig.entry || sig.entry_price || sig.entry_low || 0;
    const text = `${sig.asset} ${sig.direction}\nEntry: ${entry}\nSL: ${sig.sl || 0}\nTP: ${sig.tp || 0}\nTime: ${timeStr}\nGenerated by Quantix AI`;

    try {
        await navigator.clipboard.writeText(text);
        const btn = document.getElementById('copy-signal-btn');
        const originalText = btn.innerHTML;
        btn.innerHTML = '✅ Copied!';
        setTimeout(() => btn.innerHTML = originalText, 2000);
    } catch (err) {
        console.error('Failed to copy: ', err);
    }
}

// --- TRADINGVIEW MODAL LOGIC ---

window.openTVPreview = (symbol, timeframe, entry, sl, tp, generated_at) => {
    const modal = document.getElementById('tv-modal');
    const iframe = document.getElementById('tv-iframe');

    // Format Display
    document.getElementById('modal-title').innerText = `${symbol} · ${timeframe} · TradingView Preview`;
    document.getElementById('modal-entry').innerText = parseFloat(entry).toFixed(5);
    document.getElementById('modal-sl').innerText = parseFloat(sl).toFixed(5);
    document.getElementById('modal-tp').innerText = parseFloat(tp).toFixed(5);

    const dt = new Date(generated_at);
    document.getElementById('modal-utc').innerText = dt.toISOString().replace('T', ' ').slice(0, 16);

    document.getElementById('modal-external-link').href = getTradingViewLink(symbol, timeframe);

    // Set Iframe URL (Using Widget Embed for best performance)
    const cleanSymbol = symbol.replace('/', '');
    const tvSymbol = cleanSymbol.includes(':') ? cleanSymbol : `FX:${cleanSymbol}`;
    const tf = timeframe ? timeframe.replace('M', '') : '15';

    iframe.src = `https://s.tradingview.com/widgetembed/?symbol=${tvSymbol}&interval=${tf}&theme=dark`;

    modal.classList.add('active');
    document.body.style.overflow = 'hidden'; // Prevent scroll
};

window.closeTVModal = () => {
    const modal = document.getElementById('tv-modal');
    const iframe = document.getElementById('tv-iframe');
    iframe.src = ""; // Stop iframe loading
    modal.classList.remove('active');
    document.body.style.overflow = 'auto';
};

// Close modal on background click
document.addEventListener('click', (e) => {
    const modal = document.getElementById('tv-modal');
    if (e.target === modal) closeTVModal();
});

// Tab Switching Logic
window.switchTab = (tab) => {
    activeTab = tab;

    // Update Button UI
    document.querySelectorAll('.tab-btn').forEach(btn => {
        btn.classList.remove('active');
        if (btn.innerText.toLowerCase().includes(tab)) btn.classList.add('active');
    });

    // Toggle Content
    document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));
    document.getElementById(`${tab}-tab`).classList.add('active');

    if (tab === 'history') loadHistory();
};

// --- ACTIVE TAB LOGIC ---

function isMarketOpen() {
    const now = new Date();
    const day = now.getUTCDay(); // 0 is Sunday, 6 is Saturday
    const hour = now.getUTCHours();
    // Forex: Open Sun 22:00 UTC to Fri 22:00 UTC
    if (day === 6) return false;
    if (day === 5 && hour >= 22) return false;
    if (day === 0 && hour < 22) return false;
    return true;
}

async function fetchLatestSignal() {
    const recordEl = document.getElementById('signal-record');
    const closedEl = document.getElementById('market-closed');

    if (!isMarketOpen()) {
        if (closedEl) closedEl.classList.remove('hidden');
        if (recordEl) recordEl.classList.add('hidden');
        return;
    }

    try {
        const response = await fetch(LIVE_API_URL);
        if (!response.ok) throw new Error("API Offline");
        const data = await response.json();

        if (data.status === "MARKET_CLOSED") {
            if (closedEl) closedEl.classList.remove('hidden');
            if (recordEl) recordEl.classList.add('hidden');
            return;
        }

        displayActiveSignal(data);
    } catch (error) {
        console.error("Fetch failed:", error);
    }
}

function displayActiveSignal(record) {
    document.getElementById('market-closed').classList.add('hidden');
    document.getElementById('signal-record').classList.remove('hidden');

    const ts = record.executed_at || record.timestamp || record.generated_at;
    const dateObj = (ts && !isNaN(new Date(ts))) ? new Date(ts) : null;
    if (dateObj) {
        const dStr = dateObj.toLocaleDateString('en-CA');
        const tStr = dateObj.toLocaleTimeString('en-GB', { hour12: false, timeZone: 'UTC' });
        document.getElementById('record-generated-at').innerText = `${dStr} ${tStr} UTC`;
    }

    const asset = record.asset || 'EUR/USD';
    const timeframe = record.timeframe || 'M15';
    document.getElementById('record-asset').textContent = asset;
    document.getElementById('record-tf').textContent = timeframe;

    const dirText = document.getElementById('dir-text');
    const direction = record.direction || "BUY";
    const isBuy = direction === 'BUY';
    dirText.textContent = isBuy ? "🟢 BUY" : "🔴 SELL";
    dirText.className = isBuy ? "BUY" : "SELL";

    const f = (val) => val ? parseFloat(val).toFixed(5) : "---";
    const entry = record.entry || record.entry_low || record.entry_price || 0;
    const tp = record.tp || 0;
    const sl = record.sl || 0;

    document.getElementById('record-entry').textContent = f(entry);
    document.getElementById('record-tp').textContent = f(tp);
    document.getElementById('record-sl').textContent = f(sl);

    const conf = record.confidence || record.ai_confidence || 0;
    document.getElementById('record-confidence').textContent = conf > 0 ? `${conf}%` : "Alpha v1";
    document.getElementById('record-strategy').textContent = record.strategy || "Quantix Alpha v1";
    document.getElementById('strength-text').textContent = conf > 0 ? `(${conf}%)` : "(Alpha)";

    // Update Action Buttons
    const tvBtn = document.getElementById('tv-link-active');
    tvBtn.onclick = (e) => {
        e.preventDefault();
        openTVPreview(asset, timeframe, entry, sl, tp, ts);
    };

    document.getElementById('copy-signal-btn').onclick = () => copySignalToClipboard(record);

    const statusEl = document.getElementById('record-status-detailed');
    const state = record.state || 'WAITING_FOR_ENTRY';

    let label = "Checking...";
    let color = "var(--text-secondary)";

    if (state === 'WAITING_FOR_ENTRY') { label = "⏳ PENDING (Waiting Entry)"; color = "var(--primary-blue)"; }
    else if (state === 'ENTRY_HIT') { label = "🚀 ACTIVE (Monitoring)"; color = "var(--accent-green)"; }
    else if (state === 'TP_HIT') { label = "🎯 SUCCESS (Target Hit)"; color = "var(--accent-green)"; }
    else if (state === 'SL_HIT') { label = "🛑 STOPPED (Exit Hit)"; color = "var(--accent-red)"; }
    else if (state === 'CANCELLED') { label = "⚪ NO TRADE (Expired)"; }

    statusEl.innerText = label;
    statusEl.style.color = color;
}

// --- HISTORY TAB LOGIC ---

async function loadHistory() {
    const tbody = document.getElementById('history-body');
    tbody.innerHTML = '<tr><td colspan="8" style="text-align:center">⏳ Fetching History...</td></tr>';

    try {
        const asset = document.getElementById('filter-asset').value;
        const outcome = document.getElementById('filter-outcome').value;
        const sort = document.getElementById('filter-sort').value;

        let url = `${SB_URL}?select=*&limit=100`;
        const sortOrder = sort === 'asc' ? 'asc' : 'desc';
        url += `&order=generated_at.${sortOrder}`;

        if (asset !== 'ALL') {
            const dbAsset = asset.replace('/', '');
            url += `&asset=eq.${dbAsset}`;
        }

        if (outcome !== 'ALL') {
            const stateMap = {
                'PROFIT': 'TP_HIT',
                'LOSS': 'SL_HIT',
                'CANCELLED': 'CANCELLED',
                'PENDING': 'WAITING_FOR_ENTRY'
            };
            const mappedState = stateMap[outcome];
            if (mappedState) {
                if (outcome === 'PENDING') {
                    url += `&state=in.(WAITING_FOR_ENTRY,ENTRY_HIT)`;
                } else {
                    url += `&state=eq.${mappedState}`;
                }
            }
        }

        const res = await fetch(url, {
            headers: {
                "apikey": SB_KEY,
                "Authorization": `Bearer ${SB_KEY}`
            }
        });

        if (!res.ok) throw new Error(`Supabase Error: ${res.status}`);

        let signals = await res.json();
        tbody.innerHTML = "";

        if (!signals || signals.length === 0) {
            tbody.innerHTML = '<tr><td colspan="8" style="text-align:center">No records found.</td></tr>';
            return;
        }

        signals.forEach(sig => {
            const dt = new Date(sig.generated_at);
            if (isNaN(dt.getTime())) return;

            const dStr = dt.toLocaleDateString('en-CA');
            const tStr = dt.toLocaleTimeString('en-GB', { hour12: false, timeZone: 'UTC' }).slice(0, 5);

            const entry = sig.entry_price || sig.entry_low || 0;
            const sl = sig.sl || 0;
            const tp = sig.tp || 0;
            const rr = calculateRR(entry, sl, tp, sig.direction);
            const tf = sig.timeframe || 'M15';

            const mapping = mapState(sig.state);
            const row = document.createElement('tr');
            row.innerHTML = `
                <td data-label="Date/Time" class="mono" style="font-size: 0.8rem">${dStr} ${tStr}</td>
                <td data-label="Symbol"><a href="#" class="tv-preview-link" style="text-decoration:none; color:inherit;"><b>${sig.asset}</b> 📈</a></td>
                <td data-label="Side"><span class="direction-tag tag-${(sig.direction || 'BUY').toLowerCase()}">${sig.direction || 'BUY'}</span></td>
                <td data-label="Entry" class="mono">${parseFloat(entry).toFixed(5)}</td>
                <td data-label="SL" class="mono">${parseFloat(sl).toFixed(5)}</td>
                <td data-label="TP" class="mono">${parseFloat(tp).toFixed(5)}</td>
                <td data-label="R:R" class="mono">1 : ${rr}</td>
                <td data-label="Outcome"><span class="outcome-badge outcome-${mapping.class}">${mapping.label}</span></td>
            `;

            // Add Modal Trigger to the icon link
            row.querySelector('.tv-preview-link').onclick = (e) => {
                e.preventDefault();
                openTVPreview(sig.asset, tf, entry, sl, tp, sig.generated_at);
            };

            tbody.appendChild(row);
        });

    } catch (e) {
        console.error("History fetch error:", e);
        tbody.innerHTML = `<tr><td colspan="8" style="text-align:center; color:var(--accent-red)">⚠️ Error loading history</td></tr>`;
    }
}

function mapState(state) {
    if (state === 'TP_HIT') return { label: 'Successful', class: 'tp' };
    if (state === 'SL_HIT') return { label: 'Not Successful', class: 'sl' };
    if (state === 'CANCELLED') return { label: 'No Trade', class: 'expired' };
    return { label: 'Pending', class: 'pending' };
}

// Initial Run
document.addEventListener('DOMContentLoaded', () => {
    fetchLatestSignal();

    const fa = document.getElementById('filter-asset');
    const fo = document.getElementById('filter-outcome');
    const fs = document.getElementById('filter-sort');

    if (fa) fa.addEventListener('change', loadHistory);
    if (fo) fo.addEventListener('change', loadHistory);
    if (fs) fs.addEventListener('change', loadHistory);

    setInterval(() => {
        if (activeTab === 'active') fetchLatestSignal();
    }, 60000);
});
